version: '2'
services:
    minhaloja-app:
        image: minhaloja
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://minhaloja-mysql:3306/minhaloja?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    minhaloja-mysql:
        extends:
            file: mysql.yml
            service: minhaloja-mysql
